/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "timesync.h"


int
timesync_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	char *ptimesync_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, timesync, version_timesync, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = ptimesync_1((void*)&ptimesync_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
	return *result_1;
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	int res = timesync_1 (host);
//	size_t sres = strftime( time, 100, "%H:%M:%S" , localtime(time) );
	printf ("%d\n", res);
exit (0);
}
