/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "timesync.h"
#include <time.h>
#include <errno.h>

long 
*timesync_1(char *host)
{
	CLIENT *clnt;
	long  *result_1;
	char *ptimesync_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, timesync, version_timesync, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = ptimesync_1((void*)&ptimesync_1_arg, clnt);
	if (result_1 == (long *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
	return result_1;
}


int
main (int argc, char *argv[])
{
	char *host;
	char *timeStr = (char *) malloc(10);
	struct timeval setHora;
	long *res;
	size_t sres;
	time_t actual;

	if (argc < 2) {
		printf ("usage: %s server_host\nAumenta la hora local en 3600 segundos\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	
	actual = time(NULL);
	sres = strftime( timeStr, 10, "%H:%M:%S" ,  localtime(&actual) );
	printf ("Hora actual: %s\n", timeStr);
	
	printf ("Consultando el servidor servidor [%s]... \n", host);
	res = timesync_1 (host);
	
	sres = strftime( timeStr, 10, "%H:%M:%S" ,  localtime((time_t*)res) );
	printf ("Seteando la hora: %s ...\n", timeStr);
	
	setHora.tv_sec = *res ;
	setHora.tv_usec = 0;
	if (settimeofday(&setHora,NULL) == -1 ) {
		printf("No me acordaba como gestionar los códigos de errores. Tenés que ser adminstrador.");
		exit(-1);
	}
	actual = time(NULL);
	sres = strftime( timeStr, 10, "%H:%M:%S" ,  localtime(&actual) );
	printf ("Hecho. La hora actual es: %s ...\n", timeStr);
	free(timeStr);
exit (0);
}

