/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "timesync.h"

long *
ptimesync_1_svc(void *argp, struct svc_req *rqstp)
{
	static long  result;

	result = ((long) time(NULL)) +3600; 

	return &result;
}

