/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SINC_H_RPCGEN
#define _SINC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define SINC_HORA 0x20000001
#define VERSION_SINC_HORA 1

#if defined(__STDC__) || defined(__cplusplus)
#define horaActual 1
extern  time_t * horaactual_1(void *, CLIENT *);
extern  time_t * horaactual_1_svc(void *, struct svc_req *);
extern int sinc_hora_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define horaActual 1
extern  time_t * horaactual_1();
extern  time_t * horaactual_1_svc();
extern int sinc_hora_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SINC_H_RPCGEN */
