/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "sinc.h"
#include "time.h"
#include "stdio.h"

void
sinc_hora_1(char *host)
{
	CLIENT *clnt;
	time_t  *result_1;
	char *horaactual_1_arg;
	struct tm * timeinfo;

#ifndef	DEBUG
	clnt = clnt_create (host, SINC_HORA, VERSION_SINC_HORA, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = horaactual_1((void*)&horaactual_1_arg, clnt);
	if (result_1 == (time_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	timeinfo = localtime ( &rawtime );
	printf("La hora actual es: %s\n", asctime(timeinfo));
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	sinc_hora_1 (host);
exit (0);
}
