/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TIMESYNC_H_RPCGEN
#define _TIMESYNC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define TIMESYNCPROG 99
#define TIMESYNCVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define TIMESYNC 1
extern  long * timesync_1(void *, CLIENT *);
extern  long * timesync_1_svc(void *, struct svc_req *);
extern int timesyncprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define TIMESYNC 1
extern  long * timesync_1();
extern  long * timesync_1_svc();
extern int timesyncprog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TIMESYNC_H_RPCGEN */
