/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "timesync.h"

long *
timesync_1_svc(void *argp, struct svc_req *rqstp)
{
	static long result;
	static int cant_peticiones = 0;

	result = time(NULL);

	printf("%d - Petición recibida. Se devuelve %d\n",
		cant_peticiones, result);
	cant_peticiones++;

	return &result;
}
