/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdio.h>
#include "timesync.h"


void
timesyncprog_1(char *host)
{
	CLIENT *clnt;
	long  *result_1;
	char *timesync_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, TIMESYNCPROG, TIMESYNCVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = timesync_1((void*)&timesync_1_arg, clnt);
	if (result_1 == (long *) NULL) {
		clnt_perror (clnt, "Falló la llamada RPC");
	}

	printf("Hora del servidor: %d\n", *result_1);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

int main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("uso: %s server_host\n", argv[0]);
		exit (1);
	}

	host = argv[1];
	timesyncprog_1 (host);
	exit (0);
}

